name: Extract Clickarmour.zip

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Unzip Clickarmour.zip
        run: unzip Clickarmour.zip -d Clickarmour_unzipped/

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Unzipped Files
        run: |
          git add Clickarmour_unzipped/
          git commit -m "Extracted Clickarmour.zip via GitHub Actions"
          git push
